### ISSUE TITLE
マイページのメニューレイアウト

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/Eccube-Styleguide#100]
お気に入り機能を無効にした場合、メニューからお気に入りは削除されて表示されます。

![mypage](https://cloud.githubusercontent.com/assets/12592005/25320565/38a11756-28e3-11e7-8ac9-30f2badd1911.png)

* お気に入りを有効時
![mypage2](https://cloud.githubusercontent.com/assets/12592005/25320588/6496e994-28e3-11e7-8b0e-64d781add238.png)

**Comment by yasui05821** [comment]
スタイルガイドにお気に入り機能無効状態のコンポーネントを追加しました。

9.1.2 マイページ（お気に入り機能無効）
http://eccube3-styleguide.herokuapp.com/#!/section/9.1
