### ISSUE TITLE
改善要望：エラーメッセージのクラスの共通化

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/Eccube-Styleguide#114]
会員登録画面のように、
http://eccube3-styleguide.herokuapp.com/moc/guest/register/error/

入力フォームのエラーメッセージでは
```
<div class="ec-input">
  <input type="text">
  <p class="errorMail">同じメールアドレスを入力してください。</p>
</div>
```
の`errorMail`のように、項目ごとにクラスが定義さてれいますが、エラー時のクラスは共通化できないでしょうか。

```
{{ form_errors(form.email.first) }}
```
で出力するので、どの項目のエラーも
```
<p class="error">同じメールアドレスを入力してください。</p>
```
のように出力できれば助かります。

**Comment by yasui05821** [comment]
@chihiro-adachi 
改善要望ありがとうございます。

.errorMailのように、項目ごとにクラスが定義していたところは
`.ec-errorMessage`で統一しました。

```
<div class="ec-input error">
  <input type="text">
  <p class="ec-errorMessage">有効なメールアドレスではありません。</p>
</div>

```

エラーの際の仕様としては、
 `.ec-input` に `.error` を付与することでフォームのスタイルが変わり
かつ、 `.ec-errorMessage` がdisplay:blockに変わる仕様になっております。


<img width="699" alt="2017-05-23 19 21 16" src="https://cloud.githubusercontent.com/assets/13504241/26350113/09aff6da-3fed-11e7-91d7-e6db5464d89c.png">

もしクラス側での制御よりもPHP側での制御を中心にするほうがやりやすい場合、CSSでの表示制御を解除しますのでその旨ご連絡ください。

新規登録
http://eccube3-styleguide-dev.herokuapp.com/moc/guest/register/
http://eccube3-styleguide-dev.herokuapp.com/moc/guest/register/error/

お届け先編集
http://eccube3-styleguide-dev.herokuapp.com/moc/user/address/edit/
http://eccube3-styleguide-dev.herokuapp.com/moc/user/address/edit/error/

ログイン
http://eccube3-styleguide-dev.herokuapp.com/moc/guest/login/
http://eccube3-styleguide-dev.herokuapp.com/moc/guest/login/error/

お問い合わせ
http://eccube3-styleguide-dev.herokuapp.com/moc/guest/contact/
http://eccube3-styleguide-dev.herokuapp.com/moc/guest/contact/error/

**Comment by chihiro-adachi** [comment]
@yasui05821 
ご対応ありがとうございます！

> もしクラス側での制御よりもPHP側での制御を中心にするほうがやりやすい場合、CSSでの表示制御を解除しますのでその旨ご連絡ください。

エラーがない場合は、エラーメッセージ自体出力されないので、おそらくCSSでの表示制御は不要かな、と思いますが、いちど挙動確認してみますね。

**Comment by chihiro-adachi** [comment]
@yasu
https://github.com/EC-CUBE/ec-cube/pull/2335 で取り込んでみました。

挙動も確認してみましたが、CSSの表示制御は不要かとおもいます。
どうぞ宜しくお願いします。

**Comment by chihiro-adachi** [comment]
@yasui05821 
ヘッダーの検索部分(キーワード入力)が落ちちゃってますね。

![image](https://cloud.githubusercontent.com/assets/8196725/26390094/feddc312-4097-11e7-85f6-6dca75b711e7.png)

ご確認いただけますと幸いです。

**Comment by yasui05821** [comment]
@chihiro-adachi 
ご確認ありがとうございました！
CSSによる表示制御の記述を削除しました。

## ヘッダー検索のカラム落ちについて
ご報告ありがとうございます！
issueを別に立てさせて頂きました。対応次第、以下のissueにてコメント＆クローズします。
https://github.com/EC-CUBE/Eccube-Styleguide/issues/120

**Comment by chihiro-adachi** [comment]
@yasui05821 
ご対応ありがとうございます。
修正確認しました。問題ございません。

**Comment by yasui05821** [comment]
@chihiro-adachi 
確認ありがとうございました！クローズします。
