### ISSUE TITLE
改善要望：必須項目のラベルの組み方

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/Eccube-Styleguide#115]
http://eccube3-styleguide.herokuapp.com/moc/guest/register/

`必須`ラベルのhtmlが、label内に記述されていますが、
```
<dt>
  <label class="ec-label">
    お名前<span class="ec-required">必須</span>
  </label>
</dt>
```
以下のようにlabelの外にだすことは可能でしょうか？
```
<dt>
  <label class="ec-label">お名前</label>
  <span class="ec-required">必須</span>
</dt>
```

**Comment by yasui05821** [comment]
改善要望ありがとうございます。該当箇所の修正いたしましたのでクローズします。
まだ課題がありましたらリオープンしてくださいませ。


新規登録
http://eccube3-styleguide-dev.herokuapp.com/moc/guest/register/

会員情報編集
http://eccube3-styleguide-dev.herokuapp.com/moc/user/edit/

お届け先編集
http://eccube3-styleguide-dev.herokuapp.com/moc/user/address/edit/

お問い合わせ
http://eccube3-styleguide-dev.herokuapp.com/moc/guest/contact/
