### ISSUE TITLE
SVGをフィル分割してIMGで

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/Eccube-Styleguide#128]
+ メリット： IMGにしたほうが、面倒になるがコード上がシンプルになる
+ デメリット： 本体側のリポジトリに渡すのに、画像ファイルも管理しなければいけなくなる

**Comment by mikakane** [comment]
SVG ファイル分割して、設置。
HTMLからはファイル参照する形で。

**Comment by mikakane** [comment]
eccube_hat などの 使っていないアイコンは 捨ててもよい

**Comment by yasui05821** [comment]
対応しました。issueクローズします。
http://eccube3-styleguide-dev.herokuapp.com/#/section/4.1
