### ISSUE TITLE
Fontのデフォルトの並びを変更する

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/Eccube-Styleguide#129]
Fontの呼び出し方法レベルでの変更は行わないが
デフォルトで記載しているフォントの順番や内容について見直しを行う

**Comment by mikakane** [comment]
現状
Roboto,"游ゴシック",YuGothic,Yu Gothic,"ヒラギノ角ゴ ProN W3",Hiragino Kaku Gothic ProN,Arial,"メイリオ",Meiryo,sans-serif;

**Comment by okazy** [comment]
3系とあわせる
