### ISSUE TITLE
ライセンス表記を修正

### ISSUE THREAD

**Issue by mikakane** [EC-CUBE/Eccube-Styleguide#133]
LGPLに

**Comment by mikakane** [comment]
https://github.com/EC-CUBE/eccube-api/blob/master/LICENSE

**Comment by yasui05821** [comment]
comporser.json、pacage.jsonの中で記述されているlicenceを"LGPL"に書き換える
ec-cubeリポジトリ内にあるLICENSE.txtをコピー持してこのリポジトリにも置く
