### ISSUE TITLE
セレクトボックスの矢印表示

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/Eccube-Styleguide#134]
WebKit系のブラウザでセレクトボックスを表示させると矢印が表示されていない。

http://eccube3-styleguide-dev.herokuapp.com/#/section/3.2.4

<img width="371" alt="capture" src="https://user-images.githubusercontent.com/12592005/27162937-14245fbe-51bf-11e7-9269-66c73582d656.png">

**Comment by yasui05821** [comment]
@k-yamamura 
矢印が表示されるよう対応しました。クローズします。
http://eccube3-styleguide-dev.herokuapp.com/#/section/3.2.4
