### ISSUE TITLE
お問い合わせのテキストエリア

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/Eccube-Styleguide#146]
お問い合わせ内容が、textareaではなくinput type="text"になっている。

http://eccube3-styleguide.herokuapp.com/moc/guest/contact/

![image](https://user-images.githubusercontent.com/8196725/29916630-484ef3c4-8e7a-11e7-9e11-cdbea44f5464.png)

**Comment by yasui05821** [comment]
@chihiro-adachi 
textareaに修正しました。ご確認よろしくお願いします。
http://eccube3-styleguide-dev.herokuapp.com/moc/guest/contact/
