### ISSUE TITLE
カート商品を減らす「-」ボタンの無効化状態

### ISSUE THREAD

**Issue by kiy0taka** [EC-CUBE/Eccube-Styleguide#147]
以下のように商品が1つだけのときに数量を減らすボタンを無効化したい

<img width="905" alt="screen shot 2017-09-01 at 15 37 47" src="https://user-images.githubusercontent.com/57504/29958077-d954fc90-8f2b-11e7-9d9a-54aa5cb8312a.png">

**Comment by yasui05821** [comment]
@kiy0taka 
カート内商品が１の場合のスタイルを追加しました。ご確認よろしくお願いします。
http://eccube3-styleguide-dev.herokuapp.com/#/section/15.1.5
