### ISSUE TITLE
Myページ ログインフォーム .ec-login  height の設定

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/Eccube-Styleguide#148]
**次回から自動的にログインする** というチェックボックスは設定により非表示になる場合があるため、 height の値は決め打ちにしない方が良い

![2017-09-01 15 46 03](https://user-images.githubusercontent.com/815715/29958328-372f6d72-8f2d-11e7-8414-2a8dc1f3dc6f.png)

**Comment by yasui05821** [comment]
@nanasess 
heightが固定されないように修正しました。

▼スタイルガイド
http://eccube3-styleguide-dev.herokuapp.com/#/section/6.1
▼mocページ(ログイン)
http://eccube3-styleguide-dev.herokuapp.com/moc/guest/login/
