### ISSUE TITLE
Myページ index 購入履歴の無い場合

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/Eccube-Styleguide#149]
購入履歴が無い場合は **ご注文履歴がありません。** というメッセージを表示するが、スタイルガイドに該当の定義が無い

![2017-09-01 15 51 20](https://user-images.githubusercontent.com/815715/29958435-c97e9158-8f2d-11e7-971a-33922e222e7e.png)

**Comment by nanasess** [comment]
お気に入りも同様

**Comment by yasui05821** [comment]
@nanasess 
各画面のmocを作成しました。ご確認よろしくお願いします。

▼ご注文履歴がない場合
http://eccube3-styleguide-dev.herokuapp.com/moc/user/history/empty/

▼お気に入り商品がない場合
http://eccube3-styleguide-dev.herokuapp.com/moc/user/favorite/empty/
