### ISSUE TITLE
Myページ index, history 規格有り商品の表示

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/Eccube-Styleguide#150]
購入履歴の商品に規格がある場合、スタイルガイドに該当の定義が無い

- 規格なし(現行のスタイルガイドの表示)
- 規格1 のみの場合
- 規格1, 規格2 の両方が存在する場合

上記3パターンの定義が必要

![2017-09-01 15 56 25](https://user-images.githubusercontent.com/815715/29958600-76e51e2a-8f2e-11e7-882b-b121e6d1100f.png)

**Comment by yasui05821** [comment]
@nanasess 
スタイルガイドに購入履歴の規格について定義しました。
あわせて購入履歴そのもののマークアップやCSSを少し修正しました。

サンプルコードに規格1のみ, 規格1と規格2 の両方が存在する場合の2パターンを用意しました。
ご確認よろしくお願いします。
http://eccube3-styleguide-dev.herokuapp.com/#/section/16.1
