### ISSUE TITLE
Myページ お気に入り一覧の表示

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/Eccube-Styleguide#151]
お気に入りが2個の場合、左右に分かれてしまう

<img width="1190" alt="2017-09-04 11 22 33" src="https://user-images.githubusercontent.com/815715/30009475-9da67a04-9163-11e7-9337-c7b0215cf2ef.png">

**Comment by yasui05821** [comment]
@nanasess 
お気に入り商品を2個にして確認したのですが、左右に分かれてしまうバグが再現できませんでした。
念のためmocのお気に入りページ商品２つ表示に変更してみました。ご確認よろしくお願いします。
http://eccube3-styleguide-dev.herokuapp.com/moc/user/favorite/
