### ISSUE TITLE
注文内容確認画面のエラー表示

### ISSUE THREAD

**Issue by kiy0taka** [EC-CUBE/Eccube-Styleguide#153]
<img width="1106" alt="screen shot 2017-09-04 at 17 43 20" src="https://user-images.githubusercontent.com/57504/30018628-943873c0-9198-11e7-9966-626fb3321b85.png">

**Comment by yasui05821** [comment]
@kiy0taka 
注文確認画面でエラーが表示状態のmocページを作成しました。ご確認よろしくお願いします。
http://eccube3-styleguide-dev.herokuapp.com/moc/guest/cart4/error/
