### ISSUE TITLE
ヘッダーのカートエリアの表示について

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/Eccube-Styleguide#174]
「税込」ラベルが10,000円以上だと改行表示されている。
<img width="315" alt="capture" src="https://user-images.githubusercontent.com/12592005/31000918-82cac328-a51a-11e7-8a67-2dae12abe639.png">

現状は以下の通りです。
<img width="309" alt="capture2" src="https://user-images.githubusercontent.com/12592005/31000923-8f8e9b48-a51a-11e7-95bc-009b86d0fa85.png">

**Comment by yasui05821** [comment]
@k-yamamura 
改行されないよう修正しました。クローズします。
http://eccube3-styleguide-dev.herokuapp.com/moc/
