### ISSUE TITLE
カテゴリのプルダウンが展開されない

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/Eccube-Styleguide#183]
カテゴリのプルダウンが展開されませんでした。
(2/22時点のコードをコンパイル、適用して確認)

### その他
- 3.0系では、cssでプルダウンの表示制御をしていたと思います。
- プルダウンが動作しない場合、CIテストがNGとなってしまうため本体に取り込めません。
早めにfixしたいと考えています。

### 期待結果
![image](https://user-images.githubusercontent.com/16891862/36654379-8e8fa4ac-1aff-11e8-9d45-3ae9295ba7d5.png)

**Comment by yasui05821** [comment]
@ryo-endo 
申し訳ありません。修正分を反映し、プルダウンの動作確認を行いました。
ご確認よろしくお願いします。
http://eccube3-styleguide.herokuapp.com/moc/
