### ISSUE TITLE
ショッピングカートでカートが別れた場合の調整

### ISSUE THREAD

**Issue by okazy** [EC-CUBE/Eccube-Styleguide#188]
## 概要
販売種別が違う商品がカートに入るとカートが別れるようになりました。
カートが別れる場合のデザイン・コーディングで修正したほうがいいところがあれば修正をお願いしたいです。

- moc
  - http://eccube3-styleguide.herokuapp.com/moc/guest/cart1/
- 本体のtwigファイル
  - `/src/Eccube/Resource/template/default/Cart/index.twig`
- 開発中のページ
  - http://kj3n.ec-cube.net/cart
  - 再現方法
    1. 管理画面から販売種別が販売種別Bの商品を作成する。
      - http://kj3n.ec-cube.net/admin/product/product/new
    1. 商品一覧から販売種別Aの商品（初期登録されているものは全てAです）と先ほど作成した販売種別Bの商品をカートに入れる
      - http://kj3n.ec-cube.net/products/list
    1. カートを確認する
      - http://kj3n.ec-cube.net/cart

![image](https://user-images.githubusercontent.com/16895409/42080595-2e1147be-7bbe-11e8-9c8a-6e989ca5fbab.png)

**Comment by yasui05821** [comment]
スタイルガイド修正の時にまとめて対応

**Comment by okazy** [comment]
対応ありがとうございます。
クローズします。
