### ISSUE TITLE
ご注文手続き画面（お客様情報変更）の調整

### ISSUE THREAD

**Issue by okazy** [EC-CUBE/Eccube-Styleguide#189]
## 概要
非会員購入の場合、ご注文手続き画面でお客様情報の編集ができます。
「変更」ボタン押下で編集エリアが出てくるのですが、フォームが崩れてしまっています。

こちらのフォームは「変更」ボタン押下時に動的に生成されるようになっています。
EC-CUBE本体への組み込みが難しい場合にはhtmlソースをいただけましたら弊社側で組み込みいたします。

- moc
  - http://eccube3-styleguide.herokuapp.com/moc/guest/cart4/
- 本体のtwigファイル
  - `/src/Eccube/Resource/template/default/Shopping/index.twig` 246行目付近
- 開発中のページ
  - http://kj3n.ec-cube.net/shopping
  - 再現方法
    1. ログインせず非会員のまま注文手続き画面に進む
    1. お客様情報の「変更」ボタンを押下する

<img width="1187" alt="2018-07-09 10 00 32" src="https://user-images.githubusercontent.com/16895409/42426414-c4a9222c-8362-11e8-8ec7-ab6f615f9c5b.png">

**Comment by yasui05821** [comment]
@okazy 
ご提示頂いている再現方法を実行しましたが、再現できませんでした。

> ログインせず非会員のまま注文手続き画面に進む

【1】http://kj3n.ec-cube.net/shopping へアクセス
「現在カート内に商品はございません。」と表示され、注文手続き画面に進むことができない

【2】カートに商品を追加
1でカートの空状態であることが原因だと考え、カートに商品を追加してみようとしたのですが「カートの追加に失敗しました」というエラーのポップアップが出てしまい商品をカートに追加すること自体ができないようです。

<img width="913" alt="2018-07-20 17 14 58" src="https://user-images.githubusercontent.com/13504241/42991441-823301a6-8c40-11e8-9e8a-6b5eeea5379c.png">

ご注文手続き画面（お客様情報変更）を再現できる方法について改めてご教示いただきたいです。
よろしくお願い致します。

**Comment by okazy** [comment]
@yasui05821 ご確認ありがとうございます。

> 【1】

はい、商品を追加してから購入フローに進んでいただく必要があります。

> 【2】

エラーメッセージがわかりにくくてすみません、規格を選択してから商品追加をお願いできますでしょうか？

どうぞよろしくお願いいたします。

**Comment by yasui05821** [comment]
http://kj3n.ec-cube.net/mypage/delivery/new　:SP画面と同様になるように調整

**Comment by okazy** [comment]
すみません、こちらjsでフォームを作っているのですが、処理が複雑になってしまっておりますので、twig組み込みは私の方でさせていただければと思います。

**Comment by okazy** [comment]
本課題ですが、以下のプルリクにて弊社で修正できましたのでクローズとさせていただきます。
https://github.com/EC-CUBE/ec-cube/pull/3785
