### ISSUE TITLE
お届け先の複数指定のページのデザイン

### ISSUE THREAD

**Issue by okazy** [EC-CUBE/Eccube-Styleguide#191]
## 概要
こちら新規追加ページとなります。
デザインとtwigへの組み込みをよろしくお願いいたします。

- moc
  - http://eccube3-styleguide.herokuapp.com/moc/guest/cart4/add_address/
- 本体のtwigファイル
  - `/src/Eccube/Resource/template/default/Shopping/shipping_multiple.twig`
- 開発中のページ
  - http://kj3n.ec-cube.net/shopping/shipping_multiple
  - ご注文手続き画面で「お届け先を追加する」ボタンを押下

**Comment by yasui05821** [comment]
@okazy 
デザインとはどのような作業を示していますでしょうか？
確認したところmocはできているようなので、twigへの組み込みのみという認識で間違いないでしょうか？

**Comment by okazy** [comment]
@yasui05821 ご確認ありがとうございます。

はい、デザインはしていただいているのでtwigへの組み込みをお願いします。

**Comment by okazy** [comment]
取り込み済みのためクローズします。
