### ISSUE TITLE
購入フローからお届け先の追加ページのデザインの調整

### ISSUE THREAD

**Issue by okazy** [EC-CUBE/Eccube-Styleguide#192]
## 概要
購入フローからお届け先を追加するページのデザインが崩れた状態となっておりますので、スタイルガイドに合わせて調整をお願いできますでしょうか。
[マイページからお届け先追加](http://eccube3-styleguide.herokuapp.com/moc/user/address/new/)のページのデザインを流用で問題ないかと思います。

- moc
  - なし
- 本体のtwigファイル
  - `/src/Eccube/Resource/template/default/Shopping/shipping_multiple_edit.twig`
- 開発中のページ
  - http://kj3n.ec-cube.net/shopping/shipping_multiple_edit
  1. ご注文手続き画面で「お届け先を追加する」ボタンを押下してお届け先の複数指定画面へ
  1. お届け先の複数指定画面で「新規お届け先を追加する」ボタンを押下してお届け先の追加画面へ

**Comment by yasui05821** [comment]
@okazy 
購入フローからお届け先を追加するページの再現ができませんでした。

【1】http://kj3n.ec-cube.net/shopping/shipping_multiple_edit へアクセス
「現在カート内に商品はございません。」と表示され、注文手続き画面に進むことができない

【2】カートに商品を追加
1でカートの空状態であることが原因だと考え、カートに商品を追加してみようとしたのですが「カートの追加に失敗しました」というエラーのポップアップが出てしまい商品をカートに追加すること自体ができないようです。

ご注文手続き画面を表示する方法を教えて頂きたいです。

**Comment by okazy** [comment]
@yasui05821 ご確認ありがとうございます。

商品規格を選択してからカートへの追加を試していただけますでしょうか？

どうぞよろしくお願いいたします。

**Comment by okazy** [comment]
対応済み
