### ISSUE TITLE
マイページ/お届け先編集のデザインの調整

### ISSUE THREAD

**Issue by okazy** [EC-CUBE/Eccube-Styleguide#193]
## 概要
マイページのお届け先編集ページのデザインが少し崩れてしまっており、他のページに合わせて調整をお願いしたいです。

- moc
  - http://eccube3-styleguide.herokuapp.com/moc/user/address/new/
- 本体のtwigファイル
  - `/src/Eccube/Resource/template/default/Mypage/delivery_edit.twig`
- 開発中のページ
  - http://kj3n.ec-cube.net/mypage/delivery/new

**Comment by yasui05821** [comment]
@okazy 
デザインの崩れとは開発中のページで再現可能でしょうか？
http://kj3n.ec-cube.net/mypage/delivery/new
↑こちら、アクセスすると以下のように表示されてしまいます。

<img width="564" alt="2018-07-20 18 25 05" src="https://user-images.githubusercontent.com/13504241/42994850-428c1c18-8c4a-11e8-8d89-51c5241a2896.png">

再現方法について教えてください。

**Comment by okazy** [comment]
ロックオンで対応します。
