### ISSUE TITLE
画像が小さくなってしまう

### ISSUE THREAD

**Issue by mikakane** [EC-CUBE/Eccube-Styleguide#199]
以下、のサイトのように サムネイルに小さいものが有るとNG

http://kj3n.ec-cube.net/products/detail/103

**Comment by mikakane** [comment]
![2018-08-13 14 14 38](https://user-images.githubusercontent.com/1859101/44013862-4b1c16aa-9f03-11e8-9449-a9836cb0aa06.png)

**Comment by okazy** [comment]
本体へ取り込みましたのでクローズします。
