### ISSUE TITLE
トップページ

### ISSUE THREAD

**Issue by mikakane** [EC-CUBE/Eccube-Styleguide#2]
http://eccube3-styleguide.herokuapp.com/moc/

- [x] カルーセル
- [ ] カート部JS実装
- [ ] 新着情報アコーディオン transition 実装
 - [ ] 新着情報 画面幅 950 px 程度でアイコンが落ちる問題
- [ ] スライダー部下、新入荷商品特集の箇所 コンテナに沿わせる。
- [ ] "足の透かし模様が美しいミニテーブル" 箇所のパディング整える
- [ ] レスポンシブ時の新着情報
- [ ]  下の写真が12個並ぶブロック　レスポンシブ対応
- [ ] SP 版の Slide Navi  transition対応

**Comment by yasui05821** [comment]
画面幅が1000px以下になるとTOPのカートが段落ちするのを修正
