### ISSUE TITLE
[new-design]スライド

### ISSUE THREAD

**Issue by yasui05821** [EC-CUBE/Eccube-Styleguide#206]
簡易内容になります。後ほどMTGにて詳細お伝えします。 :bow:

▼デザイン
<img width="649" alt="2018-08-22 11 50 04" src="https://user-images.githubusercontent.com/13504241/44440086-8a48b900-a601-11e8-9411-fd8693c0067e.png">

## 相談項目
- 画面幅が大きくなった場合の表示(横幅をどこまで表示させるのか)
- 工数について

**Comment by okazy** [comment]
お打ち合わせにて
  - PCとSPは同じ画像を使用する
  - PCは横の画像も表示
    - コンテナサイズの3倍まで
