### ISSUE TITLE
[new-design]カテゴリナビについて

### ISSUE THREAD

**Issue by yasui05821** [EC-CUBE/Eccube-Styleguide#207]
簡易内容になります。後ほどMTGにて詳細お伝えします。 :bow:

▼デザイン
<img width="388" alt="2018-08-22 11 56 12" src="https://user-images.githubusercontent.com/13504241/44440290-65a11100-a602-11e8-88e4-e4a96bd331c1.png">

▼現状
<img width="729" alt="2018-08-22 11 56 47" src="https://user-images.githubusercontent.com/13504241/44440361-b57fd800-a602-11e8-8968-c61a55f233be.png">

## 相談
- 工数について
- 横展開に変更可能か

**Comment by okazy** [comment]
お打ち合わせにて
  - 現在の仕様のまま
