### ISSUE TITLE
[new-design]検索のカテゴリについて

### ISSUE THREAD

**Issue by yasui05821** [EC-CUBE/Eccube-Styleguide#208]
簡易内容になります。後ほどMTGにて詳細お伝えします。 🙇

<img width="341" alt="2018-08-22 12 00 02" src="https://user-images.githubusercontent.com/13504241/44440425-fb3ca080-a602-11e8-9aec-4f091281e189.png">
<img width="319" alt="2018-08-22 12 00 15" src="https://user-images.githubusercontent.com/13504241/44440428-fd9efa80-a602-11e8-93d8-e9d95f3c7c96.png">

## 質問
- 表示は大カテゴリのみでしょうか？

**Comment by okazy** [comment]
お打ち合わせにて
  - 全カテゴリを空白のインデントで表示
  - 以下のbootstrapのコンポーネントを使用する
    - http://cccabinet.jpn.org/bootstrap4/components/input-group#buttons-with-dropdowns
