### ISSUE TITLE
ロード時にスライド画像が縦並びで一瞬表示される

### ISSUE THREAD

**Issue by yasui05821** [EC-CUBE/Eccube-Styleguide#213]

**Comment by yasui05821** [comment]
@okazy 
すみません、対応漏れてしまっていたので、改めてプルリク送りました。
ご確認よろしくお願いします。
https://github.com/EC-CUBE/ec-cube/pull/3814

**Comment by okazy** [comment]
対応ありがとうございます。
本体取り込み済みです。
