### ISSUE TITLE
ヘッダー内の検索エリア

### ISSUE THREAD

**Issue by MasumiKondo** [EC-CUBE/Eccube-Styleguide#27]
- 検索エリアselectとinputがカラム落ちする（画面幅768px～925px時に再現します）
- ここだけ他とフォントが違う（メイリオ？）

いずれもchromeで確認

**Comment by yasui05821** [comment]
対応致しました。ご確認よろしくお願いします。
http://eccube3-styleguide.herokuapp.com/moc/

**Comment by MasumiKondo** [comment]
ご対応ありがとうございます。
HTML Moc On Heroku＆Chromeで確認しました。

＞検索エリアselectとinputがカラム落ちする
　⇒devでは修正されている。masterではデバイス幅関係なく常にカラム落ちしている。

＞ここだけ他とフォントが違う（メイリオ？）
　⇒masterでは、input内だけ修正されている。devでは直っていない。
　　master、devともに、selectタグ内はメイリオのまま。

確認環境が違うようであればお聞かせください

**Comment by MasumiKondo** [comment]
カラム落ちが気になるので、一応、当方の希望をお伝えしておきます。

![header_image](https://cloud.githubusercontent.com/assets/12386971/24890685/4fb83f00-1eac-11e7-88b7-b599cebeeffc.jpg)
