### ISSUE TITLE
[TOPページ]グリッドレイアウト部分のCSSを統一させたい

### ISSUE THREAD

**Issue by MasumiKondo** [EC-CUBE/Eccube-Styleguide#29]
新入荷商品特集以下
上から、
.ec-grid3 (float)
.ec-displayC (flexbox)
.ec-grid3 (float)
.ec-displayD (flexbox)

このままでは余白を合わせる(縦のラインをあわせる)のが困難になりそうなので、
どちらかに統一したほうがいいと思います。

なお、floatに合わせるのであれば、これらの場所の場合、要素の高さを揃えるJSを読み込ませておくのが良いかもしれません。

**Comment by MasumiKondo** [comment]
#30

**Comment by yasui05821** [comment]
ec-grid3をflexboxに変更して、全体のレイアウトのCSSはflexで統一しました。
http://eccube3-styleguide.herokuapp.com/moc/

**Comment by MasumiKondo** [comment]
ご対応ありがとうございます。
遅くなりましたが確認しました。

TOPページで顕著なのですが、
3、4、6並びごとに各要素間の横余白が違うように見えます。

目立つ部分ですのでなんとか対応しておきたいのですが、
何かいい案をお持ちでないでしょうか？

**Comment by yasui05821** [comment]
ご確認ありがとうございます。

3、4、6並びごとの各要素間の横の余白、調節してみます。

**Comment by yasui05821** [comment]
http://eccube3-styleguide.herokuapp.com/moc/
調整致しました。お手すきの際にご確認よろしくお願い致します。

**Comment by MasumiKondo** [comment]
調整ありがとうございます。
確認しました。

「新入荷商品特集」の左エリア内の、2つ並んだ画像は当調整の対象外でしょうか？
また、画面幅が細くなったときに左右余白がずれてくる（異なってくる）のも対応は難しいでしょうか？

**Comment by yasui05821** [comment]
ご確認ありがとうございました。

> 「新入荷商品特集」の左エリア内の、2つ並んだ画像は当調整の対象外でしょうか？

同じになるように調整させていただきました、ご確認ください。

> また、画面幅が細くなったときに左右余白がずれてくる（異なってくる）のも対応は難しいでしょうか？

可能な限り余白が同じようになるよう調節させていただきました。
追加で気になるところがございましたらご連絡いただけると助かります。よろしくお願いします。

**Comment by yasui05821** [comment]
@MasumiKondo 
目視で可能な限り余白が揃うように調節してみました。
http://eccube3-styleguide-dev.herokuapp.com/moc/
ご確認よろしくお願いします。

また、気になるところがございましたらお気軽にリオープンしてくださいませ。
