### ISSUE TITLE
 ヘッダー部分の店名やサブタイトルが短いとカートボックスが左へずれる

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/Eccube-Styleguide#48]
<img width="1268" alt="capture" src="https://cloud.githubusercontent.com/assets/12592005/24696013/ed6c9e78-1a22-11e7-984d-2acb47dcce1f.png">

**Comment by yasui05821** [comment]
<img width="1175" alt="2017-04-07 13 57 23" src="https://cloud.githubusercontent.com/assets/13504241/24786167/39a55d7a-1b9a-11e7-89eb-ac7ce5ea85c6.png">
対応致しました。お手すきの際にご確認よろしくお願い致します。
http://eccube3-styleguide.herokuapp.com/moc/
