### ISSUE TITLE
ブロック単位で横並びする方法について

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/Eccube-Styleguide#51]
ブロックを配置するときに、利用者によってはブロック単位で横並びさせたいという要望が発生することがある。

現在のグリッドだと、
```
<div class="ec-grid2">
  <div class="ec-grid2__cell">.ec-grid2__cell</div>
  <div class="ec-grid2__cell">.ec-grid2__cell</div>
</div>
```
というようにec-gridxxで囲む必要があるが、
ブロック単位で横並びしたければレイアウトの定義時代を`<div class="ec-grid2">`で囲む必要がある。

```
<div class="ec-layoutRole__footer">
  <div class="ec-grid2">
    {# ▼Footer COLUMN#}
    {% if PageLayout.Footer %}
        {# ▼上ナビ #}
        {{ include('block.twig', {'Blocks': PageLayout.Footer}) }}
        {# ▲上ナビ #}
    {% endif %}
    {# ▲Footer COLUMN#}
    </div>
</div>
```
何か良い実現方法があるのか。

実現方法が無ければ1つのブロックで作成すれば対応可能のため、EC-CUBE3としては仕様扱いとする。

**Comment by mikakane** [comment]
現状機能にあるカート等のヘッダ部を除いて、ブロックレイアウト上での横並び は非対応でいけますでしょうか？

多分実装するとなると、ブロック側に1/2 で表示、等のプロパティ持たせる必要が出てくるので、機能追加になるかと思います。

**Comment by Yangsin** [comment]
本体側にIssueあげましたがレイアウト管理から大きく見直しをかけて、行こうと思っています。
https://github.com/EC-CUBE/ec-cube/issues/2266

これまでのフレームを大きく見直しシンプル化し、横並びにしたい場合などはブロックの中でコードでレイアウトを調整してもらうような形です。

**Comment by mikakane** [comment]
こちらレイアウトで3列対応進めたため一旦Close します。
