### ISSUE TITLE
[TOPページ]新着情報エリア周り

### ISSUE THREAD

**Issue by MasumiKondo** [EC-CUBE/Eccube-Styleguide#71]
新着情報タイトル下のborderが右端にくっついている＋右の余白が下の6分割エリアとあってない。
![news](https://cloud.githubusercontent.com/assets/12386971/24890996/1da19870-1eae-11e7-8c48-4d6adab39096.jpg)

**Comment by yasui05821** [comment]
> 新着情報タイトル下のborderが右端にくっついている　

→　DEMOサイトのデザインを確認しましたところ、borderが両端にくっつく形で点線だったので、そのように修正させていただきました。

あと、余白のほうも下の6分割の同じようになるように調整しました。
ご確認よろしくお願いします。

https://eccube3-styleguide-dev.herokuapp.com/moc/

<img width="1203" alt="2017-04-14 18 52 05" src="https://cloud.githubusercontent.com/assets/13504241/25040306/85d1ed7c-2143-11e7-859b-b4bd560009dd.png">
