### ISSUE TITLE
[スタイルガイド]ボタン内テキストの下線+商品一覧のテキストの下線+footer店名のテキストの下線

### ISSUE THREAD

**Issue by MasumiKondo** [EC-CUBE/Eccube-Styleguide#72]
http://eccube3-styleguide.herokuapp.com/#/section/6
http://eccube3-styleguide.herokuapp.com/#/section/7
http://eccube3-styleguide.herokuapp.com/#/section/11
aタグ内テキストにtext-decoration:underlineがついているのをなくしたい

**Comment by yasui05821** [comment]
スタイルガイドのaタグ内テキストにtext-decoration:underlineがつかないように修正しました。
以下のURLからご確認ください。よろしくお願いします。

◎ ボタン内テキストの下線
http://eccube3-styleguide-dev.herokuapp.com/#/section/6

◎ 商品一覧のテキストの下線、トピックパス、総計ボタン内テキストの下線
http://eccube3-styleguide-dev.herokuapp.com/#/section/7

◎ footer店名のテキストの下線
http://eccube3-styleguide-dev.herokuapp.com/#/section/11
