### ISSUE TITLE
ヘッダ部分のキーワード入力ボックスズレ

### ISSUE THREAD

**Issue by mikakane** [EC-CUBE/Eccube-Styleguide#79]
PC 版で余白多い

SP 版でアイコンが消えている。

**Comment by yasui05821** [comment]
issue #79　の対応しました。
http://eccube3-styleguide-dev.herokuapp.com/moc/

## ヘッダ部分のキーワード入力ボックス

>PC 版で余白多い

調整しました。

>SP 版でアイコンが消えている。

アイコンの色が薄いため消えているように見えていたので、カラーを調整して対応しました。


## その他の修正
- SPメニューの要素の幅、余白、ボーダー等を調整しました。
