### ISSUE TITLE
商品詳細の規格選択部分のレイアウト

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/Eccube-Styleguide#87]
モックでは商品詳細画面に規格選択プルダウンが存在していないため、
規格が存在する時のレイアウトが必要

* 規格が2つの時
http://demo3.ec-cube.net/products/detail/24
<img width="433" alt="capture1" src="https://cloud.githubusercontent.com/assets/12592005/25076390/7ac7ad80-235b-11e7-8351-e0f34fe77acd.png">

* 規格が1つの時
http://demo3.ec-cube.net/products/detail/25
<img width="430" alt="capture2" src="https://cloud.githubusercontent.com/assets/12592005/25076396/820f983c-235b-11e7-8a32-8c0623c9f615.png">

**Comment by mikakane** [comment]
横幅はボタンのサイズに併せて展開

**Comment by yasui05821** [comment]
issue #96と一緒に対応しました。
