### ISSUE TITLE
headerRole 固有の記述を極力 コンポーネント側に移す

### ISSUE THREAD

**Issue by mikakane** [EC-CUBE/Eccube-Styleguide#88]

**Comment by mikakane** [comment]
http://eccube3-styleguide.herokuapp.com/#/section/11
この辺を調整 して仕上げお願いします。

**Comment by yasui05821** [comment]
@mikakane 
調整しました。ご確認、問題なければクローズお願いします。
http://eccube3-styleguide-dev.herokuapp.com/#/section/11
