### ISSUE TITLE
商品詳細のレイアウト対応

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/Eccube-Styleguide#96]
商品詳細画面で設定可能な項目を全てセットした時のレイアウトです。
赤枠で囲っている箇所が任意項目となります。

例) http://demo3.ec-cube.net/products/detail/35
![default](https://cloud.githubusercontent.com/assets/12592005/25319720/a9a940a2-28db-11e7-8a69-43546d672a21.png)

必要最低限の項目しか設定されない画面は以下のURLより確認可能です。

例) http://demo3.ec-cube.net/products/detail/36
![2](https://cloud.githubusercontent.com/assets/12592005/25319748/079fcb22-28dc-11e7-9554-e7dd98de1f7a.png)

**Comment by yasui05821** [comment]
対応しました。

## スタイルガイド
（必要最低限の項目設定）
http://eccube3-styleguide.herokuapp.com/#!/section/14.1

## moc
(全てセット)
http://eccube3-styleguide.herokuapp.com/moc/guest/item/
