### ISSUE TITLE
カート追加後のボックスに表示する要素について

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/Eccube-Styleguide#99]
カート追加後に表示する要素として
商品画像、商品規格、金額、数量
となります。

![cartadd](https://cloud.githubusercontent.com/assets/12592005/25320468/57b51ddc-28e2-11e7-8dcd-06f6b2779161.png)

**Comment by yasui05821** [comment]
対応しました。

## スタイルガイド
- 7.3.6 カートナビゲーションのポップアップ(商品詳細)
- 7.3.7 カートナビゲーションのポップアップ(商品なし)
http://eccube3-styleguide.herokuapp.com/#!/section/7.3

## moc
カートナビゲーションのポップアップ(商品詳細)
http://eccube3-styleguide.herokuapp.com/moc/

カートナビゲーションのポップアップ(商品なし)
http://eccube3-styleguide.herokuapp.com/moc/layout/cartNavi_popupNull.html
